### ISSUE TITLE
[Bug]: In the 'Changed files' window: Uncheck some files → Ignore a file → Unchecked files are checked again

### ISSUE THREAD

**Issue by Kotsuha** [pragma-git/pragma-git#5] opened 2024-02-12 19:43 UTC
### What happened?

![pragma-issue](https://github.com/pragma-git/pragma-git/assets/10438710/f981130b-1c48-4e43-aee9-90863a6c9371)
This wouldn't necessary be an issue. Just feel a little strange. In the 'Changed files' window, if I uncheck some files and then ignore a file, the unchecked files are checked again. I'd expect they stay unchecked.

### To reproduce

1. Go to the 'Changed files' window
2. Uncheck some files
3. Ignore a file
4. Notice the unchecked files are checked again

### Expected behavior

I wish the unchecked files stay unchecked.

### System Info and Screen shots

Information
Pragma-git version:
0.9.11

Latest available version:
0.9.11 [[Download page]](https://github.com/pragma-git/pragma-git/releases/latest)

nwjs version:
0.83.0(sdk)

Platform:
win32

Git version:
git version 2.43.0.windows.1

Settings folder:
C:\Users\usr2\.Pragma-git

Log file:
C:\Users\usr2\.Pragma-git\.tmp\pragma-git-log.txt

Your system's path as seen by Pragma-git :
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\bin;
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\libnvvp;
C:\Windows\system32;
C:\Windows;
C:\Windows\System32\Wbem;
C:\Windows\System32\WindowsPowerShell\v1.0\;
C:\Windows\System32\OpenSSH\;
C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;
C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;
C:\Program Files\7-Zip;
C:\Program Files\TortoiseHg\;
C:\Program Files\Perforce\;
C:\Program Files\dotnet\;
C:\Program Files (x86)\GtkSharp\2.12\bin;
C:\Program Files\Nintendo\Nintendo Dev Interface;
C:\ProgramData\chocolatey\bin;
C:\Program Files\nvm;
C:\Program Files\nodejs;
C:\Program Files\Python3.10.6\Scripts\;
C:\Program Files\Python3.10.6\;
C:\PortableApps (CLI)\jdk-17.0.7+7\bin;
C:\PortableApps\CommonFiles\OpenJDKJRE64\bin;
C:\Program Files (x86)\Common Files\Oracle\Java\javapath;
C:\Program Files\Oracle\VirtualBox;
C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;
C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;
C:\Program Files\Go\bin;
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin;
C:\Program Files\TortoiseGit\bin;
C:\Program Files\Git\cmd;
C:\Users\usr2\AppData\Local\Microsoft\WindowsApps;
C:\Program Files\Git\bin;
C:\PortableApps (CLI)\ffmpeg;
C:\PortableApps (CLI)\sox;
C:\PortableApps (CLI)\yt-dlp;
C:\PortableApps (CLI)\livedl;
C:\PortableApps (CLI)\JetBrains.ReSharper.CommandLineTools;
C:\PortableApps (CLI)\FART;
C:\PortableApps (CLI)\jq;
C:\PortableApps (CLI)\Neovim\bin;
C:\PortableApps (CLI)\bit;
C:\PortableApps\cygwin-portable\cygwin\bin;
C:\PortableApps (Not Stealth)\Arsenal-Image-Mounter;
C:\Program Files (x86)\Vim\vim90;
C:\PortableApps\MSYS2Portable\App\msys64\usr\bin;
C:\PortableApps\MSYS2Portable\App\msys64\mingw64\bin;
C:\PortableApps\VSCode-Portable\VSCode\Code.exe;
C:\Users\usr2\go\bin;
C:\Users\usr2\AppData\Roaming\Python\Python310\Scripts;
C:\Users\usrpub\.pyenv\pyenv-win\bin;
C:\Users\usrpub\.pyenv\pyenv-win\shims;
C:\Users\usr2\.dotnet\tools;
C:\Users\usr2\AppData\Local\JetBrains\Toolbox\scripts

License:
[MIT license](chrome-extension://gboiinhcjcmbpcfnoccodedfpeecdgoa/settings.html#).

**Comment by pragma-git** [comment] 2024-02-12 22:24
Thanks for the issue report.  The gif animation was very helpful.

This is unintended behavior.  The correct behavior has been implemented, and will be released in the next version shortly

**Closed as completed by pragma-git** 2024-02-12 22:24 UTC
Labels: bug
